version: '3'
services:

  nginx-gen:
    build: ./docker-gen/
    container_name: nginx-docker-gen
    restart: always
    labels:
      - com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen
    volumes:
      - 'nginx-config:/etc/nginx/conf.d'
      - 'nginx-certs:/etc/nginx/certs'
      - 'nginx-vhosts:/etc/nginx/vhost.d'
      - 'nginx-webroot:/usr/share/nginx/html'
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
    depends_on:
      - nginx
    command: -notify-sighup nginx -watch -wait 10s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  letsencrypt:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    volumes:
      - 'nginx-config:/etc/nginx/conf.d'
      - 'nginx-certs:/etc/nginx/certs'
      - 'nginx-vhosts:/etc/nginx/vhost.d'
      - 'nginx-webroot:/usr/share/nginx/html'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-docker-gen
      - NGINX_PROXY_CONTAINER=nginx
    depends_on:
      - nginx-gen
