version: '3'
services:
  letsencrypt:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt
    volumes:
      - 'nginx-config:/etc/nginx/conf.d'
      - 'nginx-certs:/etc/nginx/certs'
      - 'nginx-vhosts:/etc/nginx/vhost.d'
      - 'nginx-webroot:/usr/share/nginx/html'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-docker-gen
      - NGINX_PROXY_CONTAINER=nginx
volumes:
  shared-volume:
  nginx-config:
  nginx-certs:
  nginx-vhosts:
  nginx-webroot:
