version: '3'
services:
  api:
    environment:
      - VIRTUAL_HOST=api.wisp.services,admin.wisp.services
      - LETSENCRYPT_HOST=api.wisp.services,admin.wisp.services
      - LETSENCRYPT_EMAIL=simon@polkaspots.com
      - LETSENCRYPT_TEST=true
    env_file:
      - production.vars
  worker:
    env_file:
      - production.vars
  dashboard:
    env_file:
      - production.vars
