version: '3'
services:
  redis:
    image: "redis:alpine"
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    volumes:
      - ./redis:/data
  db:
    image: postgres
    restart: always
    env_file:
      - production.vars
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
  api:
    restart: always
    image: "ohmimo/mimo-api:latest"
    env_file:
      - production.vars
    # ports:
    #   - "3030:3000"
    command: bash -c "sleep 10 && bundle exec rake db:create && rake db:migrate && bundle exec rake production:bootstrap && bundle exec rake assets:precompile && bundle exec puma -C /myapp/config/puma.rb"
    depends_on:
      - redis
      - db
    volumes:
        - shared-volume:/etc/mimo

  worker:
    restart: always
    image: "ohmimo/mimo-worker"
    env_file:
      - production.vars
    environment:
      - RAILS_LOG_TO_STDOUT=true
      - RAILS_SERVE_STATIC_FILES=true
      - REDIS_HOST=redis
    command: bash -c "sidekiq"
    depends_on:
      - db
      - api
      - redis

  dashboard:
    restart: always
    image: "ohmimo/mimo-dashboard"
    env_file:
      - production.vars
    environment:
      - NODE_ENV=production
    # ports:
    #   - "8082:8080"
    depends_on:
      - api
    volumes:
        - shared-volume:/etc/mimo

  web:
    restart: always
    image: 'ohmimo/mimo-nginx'
    ports:
     - "80:8080"
    depends_on:
      - api
    command: "nginx -g 'daemon off;'"

volumes:
  shared-volume:
